[package]
name = "asset-bridge-daemon"
version = "0.1.0"
edition = "2024"

[dependencies]
notify = "6.1.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.37.0", features = ["full"] }
chrono = { version = "0.4", features = ["serde"] }
